### ISSUE TITLE
Different chrome versions, the path is different on windows

### ISSUE THREAD

**Issue by Mr-xn** [x899/chrome_password_grabber#5]
it's somme not perfect in windows. beacuase i use the dev chrome and whitch path like this :
`C:\Users\mrxn\AppData\Local\Google\chrome dev\User Data\Default\ `
and the stable chrome version path is:
`C:\Users\mrxn\AppData\Local\Google\chrome\User Data\Default\ `
that's all
thanks.

**Comment by x899** [comment]
This is only for Windows. We also need to do this for Mac and Linux.
Creating another generalised issue to support chrome dev, canary and  beta.

**Comment by Mr-xn** [comment]
yeh.but i don't have a Mac or Linux Desktop ，perhaps try fix it on my VMware.
